controllers:
    resource: '@MileageBundle/Controller/'
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

mileage.api:
    resource: '@MileageBundle/API/'
    type: attribute
    prefix: /api
