services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KimaiPlugin\MileageBundle\:
        resource: '../../*'
        exclude:
            - '../../Migrations/'
            - '../../Resources/'
            - '../../DependencyInjection/'
            - '../../Controller/'
            - '../../API/'
            - '../../tests/'
            - '../../vendor/'
            - '../../tools/'
            - '../../node_modules/'
            - '../../.kimai/'
            - '../../.php-cs-fixer.dist.php'

    KimaiPlugin\MileageBundle\Service\DawarichKeyStore: '@KimaiPlugin\MileageBundle\Repository\UserSecretRepository'

    KimaiPlugin\MileageBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
        public: true

    KimaiPlugin\MileageBundle\API\:
        resource: '../../API'
        tags: ['controller.service_arguments']
        public: true
